name: yad_sys
description: "فروشگاه یادمان سیستم"
publish_to: 'none'
version: 2.5.8

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  check_vpn_connection: ^0.0.2
  connectivity_plus: ^6.0.3
  get: ^4.6.6
  http: ^1.2.1
  image_picker: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  loading_animation_widget: ^1.2.0+4
  path: ^1.8.2
  path_provider: ^2.0.15
  persian_number_utility: ^1.1.3
  shared_preferences: ^2.1.1
  show_up_animation: ^2.0.0
  simple_shadow: ^0.3.1
  smooth_page_indicator: ^1.1.0
  email_validator: ^3.0.0
  easy_loading_button: ^0.3.2
  image_cropper: ^7.1.0
  persian_datetime_picker: ^2.6.0
  flutter_svg: ^2.0.10+1
  jalali_table_calendar: ^1.3.3
  flutter_widget_from_html: ^0.15.0
  another_flushbar: ^1.12.30
  logger: ^2.2.0
  flutter_staggered_animations: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logos/

  fonts:
    - family: IranYekan
      fonts:
        - asset: assets/fonts/iranyekan.ttf